module.exports={
    USERREGISTER:'userRegister',
    EMPLOYEREGISTER:'employerRegister',
    ADDEDJOBS:'addedjobs',
    EMPLOYERPROFILE:'employerprofile',
    USERPROFILE:'userprofile',
    APPLIEDJOBS:'appliedjobs',
    RESUMEDATA:'resumedata',
    ACCEPTEDJOB:'acceptedjob',
    MACHANETEST:'machanetest'
}